### ISSUE TITLE
Not available on maven central repo 2?

### ISSUE THREAD

**Issue by amitnagesh** [cronn-de/ssh-proxy#6]
Downloading: https://repo.maven.apache.org/maven2/de/cronn/ssh-proxy/1.1/ssh-proxy-1.1.pom
[WARNING] The POM for de.cronn:ssh-proxy:pom:1.1 is missing, no dependency information available

**Comment by bwaldvogel** [comment]
Version 1.2 is available on maven central now: http://repo1.maven.org/maven2/de/cronn/ssh-proxy/1.2/
